### ISSUE TITLE
Installation issue with .net 4.5  projects

### ISSUE THREAD

**Issue by vivekjain19** [aelij/AsyncFriendlyStackTrace#8] opened 2016-04-07 11:17 UTC
Install-Package AsyncFriendlyStackTrace
Installing 'AsyncFriendlyStackTrace 1.2.0'.
Successfully installed 'AsyncFriendlyStackTrace 1.2.0'.
Adding 'AsyncFriendlyStackTrace 1.2.0' to ConsoleApplication1.
Uninstalling 'AsyncFriendlyStackTrace 1.2.0'.
Successfully uninstalled 'AsyncFriendlyStackTrace 1.2.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'AsyncFriendlyStackTrace 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.At line:1 char:1
- Install-Package AsyncFriendlyStackTrace
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by aelij** [comment] 2016-04-08 05:43
This is by design, since .NET 4.5 support has [ended](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/).

I'll consider supporting it in this library though.

**Comment by M0ns1gn0r** [comment] 2016-04-08 06:11
That's Microsoft support, so they won't fix bugs, answer your questions, etc. This doesn't mean a NuGet package should not support the '.NETFramework,Version=v4.5' target.

**Comment by abatishchev** [comment] 2016-05-14 05:24
4.5.2 is still supported indeed. Until there are technical reasona to stop supporting, it should be continued, please.

**Comment by aelij** [comment] 2016-06-08 10:07
The latest package also supports .NET 4.5.

**Closed as completed by aelij** 2016-06-08 10:07 UTC
